import type { Scheme } from "./types";

/**
 * Informal phonetic romanization -> Malayalam script. Unlike Tamil, Malayalam
 * keeps separate voiced/voiceless consonant letters, so "g/d/b" map to their
 * own glyphs instead of reusing the voiceless ones.
 */
export const malayalamScheme: Scheme = {
  consonants: {
    ksh: "ക്ഷ",
    ngg: "ങ",
    ng: "ങ",
    nj: "ഞ",
    ny: "ഞ",
    sh: "ഷ",
    gh: "ഘ",
    kh: "ഖ",
    ch: "ച",
    chh: "ഛ",
    jh: "ഝ",
    th: "ത",
    dh: "ധ",
    zh: "ഴ",
    bh: "ഭ",
    ph: "ഫ",
    gn: "ഞ",
    k: "ക",
    g: "ഗ",
    c: "ച",
    j: "ജ",
    t: "ട",
    T: "ട",
    d: "ദ",
    D: "ഡ",
    n: "ന",
    N: "ണ",
    p: "പ",
    b: "ബ",
    f: "ഫ",
    m: "മ",
    y: "യ",
    r: "ര",
    R: "റ",
    l: "ല",
    L: "ള",
    v: "വ",
    w: "വ",
    s: "സ",
    h: "ഹ",
    x: "ക്സ",
    z: "സ്",
  },
  vowelSigns: {
    aa: "ാ",
    A: "ാ",
    ee: "ീ",
    I: "ീ",
    oo: "ൂ",
    U: "ൂ",
    ai: "ൈ",
    au: "ൌ",
    E: "േ",
    O: "ോ",
    a: "",
    i: "ി",
    u: "ു",
    e: "െ",
    o: "ൊ",
  },
  independentVowels: {
    aa: "ആ",
    A: "ആ",
    ee: "ഈ",
    I: "ഈ",
    oo: "ഊ",
    U: "ഊ",
    ai: "ഐ",
    au: "ഔ",
    E: "ഏ",
    O: "ഓ",
    a: "അ",
    i: "ഇ",
    u: "ഉ",
    e: "എ",
    o: "ഒ",
  },
  virama: "്",
};
