import type { Scheme } from "./types";

/**
 * Informal phonetic romanization -> Tamil script, matching the conventions most
 * Tamil typing tools use for names (e.g. "th" -> த, "zh" -> ழ, "n" -> ன).
 * Multi-letter tokens are matched greedily (longest first) by the engine.
 */
export const tamilScheme: Scheme = {
  consonants: {
    ksh: "க்ஷ",
    ngg: "ங",
    ng: "ங",
    nj: "ஞ",
    ny: "ஞ",
    sh: "ஷ",
    ch: "ச",
    th: "த",
    dh: "த",
    zh: "ழ",
    gn: "ஞ",
    k: "க",
    g: "க",
    c: "ச",
    j: "ஜ",
    t: "ட",
    d: "ட",
    n: "ன",
    N: "ண",
    T: "ட",
    D: "ட",
    p: "ப",
    b: "ப",
    f: "ஃப",
    m: "ம",
    y: "ய",
    r: "ர",
    R: "ற",
    l: "ல",
    L: "ள",
    v: "வ",
    w: "வ",
    s: "ஸ",
    h: "ஹ",
    x: "க்ஸ",
    z: "ஸ்",
  },
  vowelSigns: {
    aa: "ா",
    A: "ா",
    ee: "ீ",
    I: "ீ",
    oo: "ூ",
    U: "ூ",
    ai: "ை",
    au: "ௌ",
    E: "ே",
    O: "ோ",
    a: "",
    i: "ி",
    u: "ு",
    e: "ெ",
    o: "ொ",
  },
  independentVowels: {
    aa: "ஆ",
    A: "ஆ",
    ee: "ஈ",
    I: "ஈ",
    oo: "ஊ",
    U: "ஊ",
    ai: "ஐ",
    au: "ஔ",
    E: "ஏ",
    O: "ஓ",
    a: "அ",
    i: "இ",
    u: "உ",
    e: "எ",
    o: "ஒ",
  },
  virama: "்",
};
